# Generated by Django 5.0.3 on 2024-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('B.Tech', 'B.Tech'), ('MBA', 'MBA'), ('M.Tech', 'M.Tech')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=500)),
            ],
        ),
    ]
